kind: Deployment
apiVersion: apps/v1
metadata:
  name: toures-balon-campana-deployment
  labels:
    app: toures-balon-campana
spec:
  replicas: 2
  selector:
    matchLabels:
      app: toures-balon-campana
  template:
    metadata:
      labels:
        app: toures-balon-campana
    spec:
      containers:
        - name: toures-balon-campana
          image: alejoab12/toures-balon-campana
          ports:
            - containerPort: 8080